version: '3.4'

services: 
  catalog-db:
    image: mongo
    
  basket-db:
    image: redis:alpine
  
  discount-db:
    image: postgres
    
  pgadmin:
    image: dpage/pgadmin4

  
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
      
  discount-api:
    image: ${DOCKER_REGISTRY-}discount-api
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile
      
  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
      
  
  portainer:
    image: portainer/portainer-ce
  
volumes:
  mongo_data:
  portainer_data:
  discount_data:
  pgadmin_data: