version: '3.4'

services:
  catalog-db:
    container_name: catalog-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
  basket-db:
    container_name: basket-db
    restart: always
    ports:
      - "6379:6379"
        
  catalog-api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:9000
      - "DatabaseSettings__ConnectionString=mongodb://catalog-db:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types" 
    depends_on:
      - catalog-db
    ports:
      - "9000:80"
  
  basket-api:
    container_name: basket-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:9001
      - "CacheSettings__ConnectionString=basket-db:6379" 
    depends_on:
      - basket-db
    ports:
      - "9001:80"
   
   
   
        
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data